### PR TITLE
Adding a scaffolder for Turbinia jobs

### PR DESCRIPTION
**Pull request by kiddinn**
Adding a new scaffolder to generate jobs for Turbinia, part of #49

### CODE REVIEW

**Comment by aarontp** [comment]
Cool!  Should we maybe have this generate the Task template at the same time?

@kiddinn: You've probably seen this already, but here's the docs on how to create a Job/Task right now:
https://github.com/google/turbinia/blob/master/docs/developing-new-tasks.md

For most of the current Jobs and Tasks, there is a 1:1 Job:Task mapping (e.g. 1 PlasoJob -> 1 PlasoTask), but we're starting to create and plan for more complex Jobs/Tasks that split up the Jobs into multiple Tasks.  There's a little more documentation on Jobs vs. Tasks here: https://github.com/google/turbinia/blob/master/docs/how-it-works.md

**Comment by kiddinn** [comment]
wIll add a task file generation to this scaffolder as well

**Comment by kiddinn** [comment]
need to rebase and add minor corrections after the push of init file changes got pushed in

**Comment by kiddinn** [comment]
again, a bunch of other files got mangled in, closing this PR and opening a new one

**Pull request closed without merging**
